package Core.java;


import java.time.LocalDate;

/**
 * Model class representing a single financial expense.
 */
public class Expense {
    
    // Encapsulated fields
    private Long id;
    private String title;
    private double amount;
    private String category;
    private LocalDate date;
    private String notes;

    // 1. Default No-Argument Constructor (Required for many frameworks like Spring/Hibernate)
    public Expense() {
    }

    // 2. Full Parameterized Constructor (Useful for manual object instantiation)
    public Expense(Long id, String title, double amount, String category, LocalDate date, String notes) {
        this.id = id;
        this.title = title;
        this.amount = amount;
        this.category = category;
        this.date = date;
        this.notes = notes;
    }

    // 3. Alternate Constructor (Commonly used when IDs are auto-generated by a database)
    public Expense(String title, double amount, String category, LocalDate date, String notes) {
        this.title = title;
        this.amount = amount;
        this.category = category;
        this.date = date;
        this.notes = notes;
    }

    // ==================== Getters and Setters ====================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        // Simple validation rule
        if (amount < 0) {
            throw new IllegalArgumentException("Amount cannot be negative");
        }
        this.amount = amount;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    // ==================== Utility Methods ====================

    // Overriding toString() for easier logging and debugging
    @Override
    public String toString() {
        return "Expense{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", amount=$" + amount +
                ", category='" + category + '\'' +
                ", date=" + date +
                ", notes='" + notes + '\'' +
                '}';
    }
}
